SET ECHO ON

SPOOL cui_schema_output.txt

drop table AUTHORITY cascade constraints purge;
drop table BIN cascade constraints purge;
drop table BIN_PROPERTY cascade constraints purge;
drop table COLLECTION_MADE cascade constraints purge;
drop table COLLECTION_ROUTE cascade constraints purge;
drop table CONTRACT cascade constraints purge;
drop table CONTRACT_WASTE_TYPE cascade constraints purge;
drop table DRIVER cascade constraints purge;
drop table OWNER cascade constraints purge;
drop table PROPERTY cascade constraints purge;
drop table PROPERTY_OWNER cascade constraints purge;
drop table STREET cascade constraints purge;
drop table SUPPLY_COST cascade constraints purge;
drop table TRUCK cascade constraints purge;
drop table TRUCK_DRIVER cascade constraints purge;
drop table WASTE_TYPE cascade constraints purge;

-- Generated by Oracle SQL Developer Data Modeler 22.2.0.165.1149
--   at:        2023-05-01 21:56:45 AEST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE authority (
    auth_name       VARCHAR2(50) NOT NULL,
    auth_ceo_fname  VARCHAR2(50) NOT NULL,
    auth_ceo_lname  VARCHAR2(50) NOT NULL,
    auth_total_area NUMBER(10) NOT NULL,
    auth_type       VARCHAR2(50) NOT NULL,
    auth_telnumber  CHAR(10) NOT NULL
);

ALTER TABLE authority
    ADD CONSTRAINT authority_type_constraint CHECK ( auth_type IN ( 'Borough', 'City'
    , 'District Council', 'Shire', 'Town' ) );

COMMENT ON COLUMN authority.auth_name IS
    'Authority Name';

COMMENT ON COLUMN authority.auth_ceo_fname IS
    'Authority CEO First Name';

COMMENT ON COLUMN authority.auth_ceo_lname IS
    'Authority CEO Last Name';

COMMENT ON COLUMN authority.auth_total_area IS
    'Authority Total Area';

COMMENT ON COLUMN authority.auth_type IS
    'Authority Type
Must be one of Borough, City, District Council, Shire or Town as defined by 
auhtority_type constraint';

COMMENT ON COLUMN authority.auth_telnumber IS
    'Authority Telephone Number';

ALTER TABLE authority ADD CONSTRAINT authority_pk PRIMARY KEY ( auth_name );

CREATE TABLE bin (
    bin_id                   NUMBER(10) NOT NULL,
    bin_size                 NUMBER(10) NOT NULL,
    waste_type_id            VARCHAR2(50 CHAR) NOT NULL,
    bin_standard_supply_cost NUMBER(10, 2) NOT NULL
);

COMMENT ON COLUMN bin.bin_id IS
    'bin surrogate key';

COMMENT ON COLUMN bin.bin_size IS
    'size of bin in Liters';

COMMENT ON COLUMN bin.waste_type_id IS
    'type of waste 

not constained to green waste, landfill, standard recycle and glass so that company can easily add new types of waste for each authority'
    ;

COMMENT ON COLUMN bin.bin_standard_supply_cost IS
    'Standard supply cost of a bin in dollars';

ALTER TABLE bin ADD CONSTRAINT bin_pk PRIMARY KEY ( bin_id );

ALTER TABLE bin ADD CONSTRAINT bin_nk UNIQUE ( bin_size,
                                               waste_type_id );

CREATE TABLE bin_property (
    bin_property_rfid_tag    CHAR(2 BYTE) NOT NULL,
    bin_property_supply_date DATE NOT NULL,
    bin_property_repl_reason VARCHAR2(50 CHAR),
    bin_property_supply_cost NUMBER(10, 2) NOT NULL,
    property_street_no       NUMBER(10) NOT NULL,
    street_id                NUMBER(10) NOT NULL,
    auth_name                VARCHAR2(50) NOT NULL,
    bin_id                   NUMBER(10) NOT NULL
);

ALTER TABLE bin_property
    ADD CONSTRAINT bin_repl_reason_const CHECK ( bin_property_repl_reason IN ( 'Bin Failure'
    , 'Damaged by owner', 'Damaged during pickup of waste', 'Stolen' ) );

COMMENT ON COLUMN bin_property.bin_property_rfid_tag IS
    'id of that particular supplied bin

Constrained by 2 bytes which is 16 hex';

COMMENT ON COLUMN bin_property.bin_property_supply_date IS
    'Date that the bin was supplied';

COMMENT ON COLUMN bin_property.bin_property_repl_reason IS
    'reason for replacing the bin 

shortended due to > 30 characters glitch

Constrained by bin_replacement_reason_constraint to be damaged by owner, bin faileure, damaged duing pickup of waste, stolen'
    ;

COMMENT ON COLUMN bin_property.bin_property_supply_cost IS
    'supply cost for a bin to a property (discussion vi), may be differnt to the contract bin supply cost '
    ;

COMMENT ON COLUMN bin_property.property_street_no IS
    'Property Street Number';

COMMENT ON COLUMN bin_property.street_id IS
    'Street ID';

COMMENT ON COLUMN bin_property.auth_name IS
    'Authority Name';

COMMENT ON COLUMN bin_property.bin_id IS
    'bin surrogate key';

ALTER TABLE bin_property ADD CONSTRAINT bin_property_pk PRIMARY KEY ( bin_property_rfid_tag
);

CREATE TABLE collection_made (
    collection_date            DATE NOT NULL,
    contract_no                NUMBER(10) NOT NULL,
    bin_property_rfid_tag      CHAR(2 BYTE) NOT NULL,
    collection_made_weight     NUMBER(10) NOT NULL,
    collection_made_overweight CHAR(1) NOT NULL
);

ALTER TABLE collection_made
    ADD CONSTRAINT cm_overweight_constr CHECK ( collection_made_overweight IN ( 'N', 'Y'
    ) );

COMMENT ON COLUMN collection_made.collection_date IS
    'Collection Date';

COMMENT ON COLUMN collection_made.contract_no IS
    'Contract Number';

COMMENT ON COLUMN collection_made.bin_property_rfid_tag IS
    'id of that particular supplied bin

Constrained by 2 bytes which is 16 hex';

COMMENT ON COLUMN collection_made.collection_made_weight IS
    'Weight of Collection Made

discussion ix is constrained by primary key of date and bin such that the same bin(which has one waste type) cannot be collected twice on the same day
';

COMMENT ON COLUMN collection_made.collection_made_overweight IS
    'Collection Made OverWeight

constrained by Y and N 
If the bin is flagged as overweight (Y) is added';

ALTER TABLE collection_made
    ADD CONSTRAINT collection_made_pk PRIMARY KEY ( collection_date,
                                                    contract_no,
                                                    bin_property_rfid_tag );

CREATE TABLE collection_route (
    collection_date DATE NOT NULL,
    contract_no     NUMBER(10) NOT NULL,
    truck_vin       CHAR(17) NOT NULL,
    driver_no       NUMBER(10) NOT NULL
);

COMMENT ON COLUMN collection_route.collection_date IS
    'Collection Date';

COMMENT ON COLUMN collection_route.contract_no IS
    'Contract Number';

COMMENT ON COLUMN collection_route.truck_vin IS
    'Truck VIN';

COMMENT ON COLUMN collection_route.driver_no IS
    'Driver Number';

ALTER TABLE collection_route ADD CONSTRAINT collection_route_pk PRIMARY KEY ( collection_date
,
                                                                              contract_no
                                                                              );

CREATE TABLE contract (
    contract_no         NUMBER(10) NOT NULL,
    contract_start_date DATE NOT NULL,
    contract_end_date   DATE NOT NULL,
    auth_name           VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN contract.contract_no IS
    'Contract Number';

COMMENT ON COLUMN contract.contract_start_date IS
    'Date that the contract started';

COMMENT ON COLUMN contract.contract_end_date IS
    'Date that the contract will (or has) ended';

COMMENT ON COLUMN contract.auth_name IS
    'Authority Name';

ALTER TABLE contract ADD CONSTRAINT contract_pk PRIMARY KEY ( contract_no );

CREATE TABLE contract_waste_type (
    cwt_id                   NUMBER(10) NOT NULL,
    contract_no              NUMBER(10) NOT NULL,
    waste_type_id            VARCHAR2(50 CHAR) NOT NULL,
    cwt_collection_cost      NUMBER(10, 2) NOT NULL,
    cwt_collection_frequency VARCHAR2(50) NOT NULL
);

ALTER TABLE contract_waste_type
    ADD CONSTRAINT cwt_collection_frequency CHECK ( cwt_collection_frequency IN ( 'Fortnightly'
    , 'Monthly', 'Weekly' ) );

COMMENT ON COLUMN contract_waste_type.cwt_id IS
    'contract waste type surrogate key';

COMMENT ON COLUMN contract_waste_type.contract_no IS
    'Contract Number';

COMMENT ON COLUMN contract_waste_type.waste_type_id IS
    'type of waste 

not constained to green waste, landfill, standard recycle and glass so that company can easily add new types of waste for each authority'
    ;

COMMENT ON COLUMN contract_waste_type.cwt_collection_cost IS
    'collection cost in dollars per kilogram';

COMMENT ON COLUMN contract_waste_type.cwt_collection_frequency IS
    'Contract Waste Type Collection Frequency

cwt_collection_frequency constrains to Weekly, Fortnightly and Monthly';

ALTER TABLE contract_waste_type ADD CONSTRAINT contract_waste_type_pk PRIMARY KEY ( cwt_id
);

ALTER TABLE contract_waste_type ADD CONSTRAINT contract_waste_type_nk UNIQUE ( waste_type_id
,
                                                                               contract_no
                                                                               );

CREATE TABLE driver (
    driver_no             NUMBER(10) NOT NULL,
    driver_contact_number CHAR(10) NOT NULL,
    driver_license_number CHAR(9) NOT NULL,
    driver_name           VARCHAR2(50) NOT NULL,
    driver_dob            DATE NOT NULL,
    driver_tfn            CHAR(9) NOT NULL
);

COMMENT ON COLUMN driver.driver_no IS
    'Driver Number';

COMMENT ON COLUMN driver.driver_contact_number IS
    'Driver Contact Number';

COMMENT ON COLUMN driver.driver_license_number IS
    'Driver License Number';

COMMENT ON COLUMN driver.driver_name IS
    'Driver Name';

COMMENT ON COLUMN driver.driver_dob IS
    'Driver Date of Birth';

COMMENT ON COLUMN driver.driver_tfn IS
    'Driver TFN';

ALTER TABLE driver ADD CONSTRAINT driver_pk PRIMARY KEY ( driver_no );

CREATE TABLE owner (
    owner_id           NUMBER(10) NOT NULL,
    owner_name         VARCHAR2(50) NOT NULL,
    owner_email        VARCHAR2(50) NOT NULL,
    owner_phone_number CHAR(10) NOT NULL
);

COMMENT ON COLUMN owner.owner_id IS
    'Owner ID';

COMMENT ON COLUMN owner.owner_name IS
    'Owner Name';

COMMENT ON COLUMN owner.owner_email IS
    'Owner Email';

COMMENT ON COLUMN owner.owner_phone_number IS
    'Owner Phone Number';

ALTER TABLE owner ADD CONSTRAINT owner_pk PRIMARY KEY ( owner_id );

CREATE TABLE property (
    property_street_no NUMBER(10) NOT NULL,
    street_id          NUMBER(10) NOT NULL,
    auth_name          VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN property.property_street_no IS
    'Property Street Number';

COMMENT ON COLUMN property.street_id IS
    'Street ID';

COMMENT ON COLUMN property.auth_name IS
    'Authority Name';

ALTER TABLE property
    ADD CONSTRAINT property_pk PRIMARY KEY ( property_street_no,
                                             street_id,
                                             auth_name );

CREATE TABLE property_owner (
    property_street_no NUMBER(10) NOT NULL,
    owner_id           NUMBER(10) NOT NULL,
    street_id          NUMBER(10) NOT NULL,
    auth_name          VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN property_owner.property_street_no IS
    'Property Street Number';

COMMENT ON COLUMN property_owner.owner_id IS
    'Owner ID';

COMMENT ON COLUMN property_owner.street_id IS
    'Street ID';

COMMENT ON COLUMN property_owner.auth_name IS
    'Authority Name';

ALTER TABLE property_owner
    ADD CONSTRAINT property_owner_pk PRIMARY KEY ( property_street_no,
                                                   street_id,
                                                   auth_name,
                                                   owner_id );

CREATE TABLE street (
    street_id          NUMBER(10) NOT NULL,
    auth_name          VARCHAR2(50) NOT NULL,
    street_name        VARCHAR2(50) NOT NULL,
    street_length      NUMBER(10) NOT NULL,
    street_road_type   VARCHAR2(50) NOT NULL,
    street_lane_number NUMBER(10) NOT NULL
);

ALTER TABLE street
    ADD CONSTRAINT street_road_type_constraint CHECK ( street_road_type IN ( 'Asphalt'
    , 'Concrete', 'Unsealed' ) );

COMMENT ON COLUMN street.street_id IS
    'Street ID';

COMMENT ON COLUMN street.auth_name IS
    'Authority Name';

COMMENT ON COLUMN street.street_name IS
    'Street Name';

COMMENT ON COLUMN street.street_length IS
    'Street Length';

COMMENT ON COLUMN street.street_road_type IS
    'Street Road Type
Constrained to be Ashpalt, concrete or unsealed by street_road_type_constraint';

COMMENT ON COLUMN street.street_lane_number IS
    'Street Lane Number';

ALTER TABLE street ADD CONSTRAINT street_pk PRIMARY KEY ( street_id,
                                                          auth_name );

CREATE TABLE supply_cost (
    supply_cost_contract NUMBER(10, 2) NOT NULL,
    cwt_id               NUMBER(10) NOT NULL,
    bin_id               NUMBER(10) NOT NULL
);

COMMENT ON COLUMN supply_cost.supply_cost_contract IS
    'bin supply cost defined in the contract';

COMMENT ON COLUMN supply_cost.cwt_id IS
    'contract waste type surrogate key';

COMMENT ON COLUMN supply_cost.bin_id IS
    'bin surrogate key';

ALTER TABLE supply_cost ADD CONSTRAINT supply_cost_pk PRIMARY KEY ( cwt_id,
                                                                    bin_id );

CREATE TABLE truck (
    truck_vin     CHAR(17) NOT NULL,
    truck_rego_no CHAR(9) NOT NULL,
    truck_make    VARCHAR2(50) NOT NULL,
    truck_model   VARCHAR2(50),
    truck_year    DATE NOT NULL
);

COMMENT ON COLUMN truck.truck_vin IS
    'Truck VIN';

COMMENT ON COLUMN truck.truck_rego_no IS
    'Truck Rego Number';

COMMENT ON COLUMN truck.truck_make IS
    'Truck Maker';

COMMENT ON COLUMN truck.truck_model IS
    'Truck Model';

COMMENT ON COLUMN truck.truck_year IS
    'Truck Year';

ALTER TABLE truck ADD CONSTRAINT truck_pk PRIMARY KEY ( truck_vin );

CREATE TABLE truck_driver (
    truck_vin             CHAR(17) NOT NULL,
    driver_no             NUMBER(10) NOT NULL,
    truck_driver_approved CHAR(1 CHAR) NOT NULL
);

ALTER TABLE truck_driver
    ADD CONSTRAINT td_approved_constraint CHECK ( truck_driver_approved IN ( 'N', 'Y'
    ) );

COMMENT ON COLUMN truck_driver.truck_vin IS
    'Truck VIN';

COMMENT ON COLUMN truck_driver.driver_no IS
    'Driver Number';

COMMENT ON COLUMN truck_driver.truck_driver_approved IS
    'Indicates if the truck diver is approved to drive that car
Constrained by Y and N in truct_driver_approved_constraint';

ALTER TABLE truck_driver ADD CONSTRAINT truck_driver_pk PRIMARY KEY ( truck_vin,
                                                                      driver_no );

CREATE TABLE waste_type (
    waste_type_id          VARCHAR2(50 CHAR) NOT NULL,
    waste_type_description VARCHAR2(50 CHAR)
);

COMMENT ON COLUMN waste_type.waste_type_id IS
    'type of waste 

not constained to green waste, landfill, standard recycle and glass so that company can easily add new types of waste for each authority'
    ;

COMMENT ON COLUMN waste_type.waste_type_description IS
    'description about the type of waste';

ALTER TABLE waste_type ADD CONSTRAINT waste_type_pk PRIMARY KEY ( waste_type_id );

ALTER TABLE contract
    ADD CONSTRAINT authority_contract FOREIGN KEY ( auth_name )
        REFERENCES authority ( auth_name );

ALTER TABLE street
    ADD CONSTRAINT authority_street FOREIGN KEY ( auth_name )
        REFERENCES authority ( auth_name );

ALTER TABLE bin_property
    ADD CONSTRAINT bin_bin_property FOREIGN KEY ( bin_id )
        REFERENCES bin ( bin_id );

ALTER TABLE collection_made
    ADD CONSTRAINT bin_collection_made FOREIGN KEY ( bin_property_rfid_tag )
        REFERENCES bin_property ( bin_property_rfid_tag );

ALTER TABLE supply_cost
    ADD CONSTRAINT bin_supp_cost FOREIGN KEY ( bin_id )
        REFERENCES bin ( bin_id );

ALTER TABLE collection_made
    ADD CONSTRAINT c_route_c_made FOREIGN KEY ( collection_date,
                                                contract_no )
        REFERENCES collection_route ( collection_date,
                                      contract_no );

ALTER TABLE collection_route
    ADD CONSTRAINT contract_collection_route FOREIGN KEY ( contract_no )
        REFERENCES contract ( contract_no );

ALTER TABLE contract_waste_type
    ADD CONSTRAINT contract_contract_waste_type FOREIGN KEY ( contract_no )
        REFERENCES contract ( contract_no );

ALTER TABLE supply_cost
    ADD CONSTRAINT cwt_supply_cost FOREIGN KEY ( cwt_id )
        REFERENCES contract_waste_type ( cwt_id );

ALTER TABLE collection_route
    ADD CONSTRAINT driver_collection_route FOREIGN KEY ( driver_no )
        REFERENCES driver ( driver_no );

ALTER TABLE truck_driver
    ADD CONSTRAINT driver_truck_driver FOREIGN KEY ( driver_no )
        REFERENCES driver ( driver_no );

ALTER TABLE property_owner
    ADD CONSTRAINT owner_property_owner FOREIGN KEY ( owner_id )
        REFERENCES owner ( owner_id );

ALTER TABLE property_owner
    ADD CONSTRAINT property_property_owner FOREIGN KEY ( property_street_no,
                                                         street_id,
                                                         auth_name )
        REFERENCES property ( property_street_no,
                              street_id,
                              auth_name );

ALTER TABLE bin_property
    ADD CONSTRAINT property_property_ownerv2 FOREIGN KEY ( property_street_no,
                                                           street_id,
                                                           auth_name )
        REFERENCES property ( property_street_no,
                              street_id,
                              auth_name );

ALTER TABLE property
    ADD CONSTRAINT street_property FOREIGN KEY ( street_id,
                                                 auth_name )
        REFERENCES street ( street_id,
                            auth_name );

ALTER TABLE collection_route
    ADD CONSTRAINT truck_collection_route FOREIGN KEY ( truck_vin )
        REFERENCES truck ( truck_vin );

ALTER TABLE truck_driver
    ADD CONSTRAINT truck_truck_driver FOREIGN KEY ( truck_vin )
        REFERENCES truck ( truck_vin );

ALTER TABLE bin
    ADD CONSTRAINT waste_type_bin FOREIGN KEY ( waste_type_id )
        REFERENCES waste_type ( waste_type_id );

ALTER TABLE contract_waste_type
    ADD CONSTRAINT waste_type_contract_waste_type FOREIGN KEY ( waste_type_id )
        REFERENCES waste_type ( waste_type_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            16
-- CREATE INDEX                             0
-- ALTER TABLE                             43
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0


SPOOL OFF

SET ECHO OFF

